// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-cms/app/core/service/internal/data/ent/category"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CategoryCreate is the builder for creating a Category entity.
type CategoryCreate struct {
	config
	mutation *CategoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CategoryCreate) SetCreatedAt(v time.Time) *CategoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableCreatedAt(v *time.Time) *CategoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CategoryCreate) SetUpdatedAt(v time.Time) *CategoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableUpdatedAt(v *time.Time) *CategoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *CategoryCreate) SetDeletedAt(v time.Time) *CategoryCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableDeletedAt(v *time.Time) *CategoryCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *CategoryCreate) SetCreatedBy(v uint32) *CategoryCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableCreatedBy(v *uint32) *CategoryCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *CategoryCreate) SetUpdatedBy(v uint32) *CategoryCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableUpdatedBy(v *uint32) *CategoryCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *CategoryCreate) SetDeletedBy(v uint32) *CategoryCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableDeletedBy(v *uint32) *CategoryCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *CategoryCreate) SetSortOrder(v uint32) *CategoryCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableSortOrder(v *uint32) *CategoryCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *CategoryCreate) SetPath(v string) *CategoryCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *CategoryCreate) SetNillablePath(v *string) *CategoryCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *CategoryCreate) SetParentID(v uint32) *CategoryCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableParentID(v *uint32) *CategoryCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *CategoryCreate) SetTenantID(v uint32) *CategoryCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableTenantID(v *uint32) *CategoryCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CategoryCreate) SetStatus(v category.Status) *CategoryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableStatus(v *category.Status) *CategoryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetIsNav sets the "is_nav" field.
func (_c *CategoryCreate) SetIsNav(v bool) *CategoryCreate {
	_c.mutation.SetIsNav(v)
	return _c
}

// SetNillableIsNav sets the "is_nav" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableIsNav(v *bool) *CategoryCreate {
	if v != nil {
		_c.SetIsNav(*v)
	}
	return _c
}

// SetIcon sets the "icon" field.
func (_c *CategoryCreate) SetIcon(v string) *CategoryCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableIcon(v *string) *CategoryCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *CategoryCreate) SetCode(v string) *CategoryCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableCode(v *string) *CategoryCreate {
	if v != nil {
		_c.SetCode(*v)
	}
	return _c
}

// SetThumbnail sets the "thumbnail" field.
func (_c *CategoryCreate) SetThumbnail(v string) *CategoryCreate {
	_c.mutation.SetThumbnail(v)
	return _c
}

// SetNillableThumbnail sets the "thumbnail" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableThumbnail(v *string) *CategoryCreate {
	if v != nil {
		_c.SetThumbnail(*v)
	}
	return _c
}

// SetPostCount sets the "post_count" field.
func (_c *CategoryCreate) SetPostCount(v uint32) *CategoryCreate {
	_c.mutation.SetPostCount(v)
	return _c
}

// SetNillablePostCount sets the "post_count" field if the given value is not nil.
func (_c *CategoryCreate) SetNillablePostCount(v *uint32) *CategoryCreate {
	if v != nil {
		_c.SetPostCount(*v)
	}
	return _c
}

// SetDirectPostCount sets the "direct_post_count" field.
func (_c *CategoryCreate) SetDirectPostCount(v uint32) *CategoryCreate {
	_c.mutation.SetDirectPostCount(v)
	return _c
}

// SetNillableDirectPostCount sets the "direct_post_count" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableDirectPostCount(v *uint32) *CategoryCreate {
	if v != nil {
		_c.SetDirectPostCount(*v)
	}
	return _c
}

// SetDepth sets the "depth" field.
func (_c *CategoryCreate) SetDepth(v int32) *CategoryCreate {
	_c.mutation.SetDepth(v)
	return _c
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableDepth(v *int32) *CategoryCreate {
	if v != nil {
		_c.SetDepth(*v)
	}
	return _c
}

// SetCustomFields sets the "custom_fields" field.
func (_c *CategoryCreate) SetCustomFields(v *map[string]string) *CategoryCreate {
	_c.mutation.SetCustomFields(v)
	return _c
}

// SetContentModelID sets the "content_model_id" field.
func (_c *CategoryCreate) SetContentModelID(v uint32) *CategoryCreate {
	_c.mutation.SetContentModelID(v)
	return _c
}

// SetNillableContentModelID sets the "content_model_id" field if the given value is not nil.
func (_c *CategoryCreate) SetNillableContentModelID(v *uint32) *CategoryCreate {
	if v != nil {
		_c.SetContentModelID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CategoryCreate) SetID(v uint32) *CategoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetParent sets the "parent" edge to the Category entity.
func (_c *CategoryCreate) SetParent(v *Category) *CategoryCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Category entity by IDs.
func (_c *CategoryCreate) AddChildIDs(ids ...uint32) *CategoryCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Category entity.
func (_c *CategoryCreate) AddChildren(v ...*Category) *CategoryCreate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// Mutation returns the CategoryMutation object of the builder.
func (_c *CategoryCreate) Mutation() *CategoryMutation {
	return _c.mutation
}

// Save creates the Category in the database.
func (_c *CategoryCreate) Save(ctx context.Context) (*Category, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CategoryCreate) SaveX(ctx context.Context) *Category {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CategoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CategoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CategoryCreate) defaults() error {
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := category.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := category.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.IsNav(); !ok {
		v := category.DefaultIsNav
		_c.mutation.SetIsNav(v)
	}
	if _, ok := _c.mutation.PostCount(); !ok {
		v := category.DefaultPostCount
		_c.mutation.SetPostCount(v)
	}
	if _, ok := _c.mutation.DirectPostCount(); !ok {
		v := category.DefaultDirectPostCount
		_c.mutation.SetDirectPostCount(v)
	}
	if _, ok := _c.mutation.Depth(); !ok {
		v := category.DefaultDepth
		_c.mutation.SetDepth(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *CategoryCreate) check() error {
	if v, ok := _c.mutation.Path(); ok {
		if err := category.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Category.path": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := category.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Category.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := category.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Category.id": %w`, err)}
		}
	}
	return nil
}

func (_c *CategoryCreate) sqlSave(ctx context.Context) (*Category, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CategoryCreate) createSpec() (*Category, *sqlgraph.CreateSpec) {
	var (
		_node = &Category{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(category.Table, sqlgraph.NewFieldSpec(category.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(category.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(category.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(category.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(category.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(category.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(category.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(category.FieldSortOrder, field.TypeUint32, value)
		_node.SortOrder = &value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(category.FieldPath, field.TypeString, value)
		_node.Path = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(category.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(category.FieldStatus, field.TypeEnum, value)
		_node.Status = &value
	}
	if value, ok := _c.mutation.IsNav(); ok {
		_spec.SetField(category.FieldIsNav, field.TypeBool, value)
		_node.IsNav = &value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(category.FieldIcon, field.TypeString, value)
		_node.Icon = &value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(category.FieldCode, field.TypeString, value)
		_node.Code = &value
	}
	if value, ok := _c.mutation.Thumbnail(); ok {
		_spec.SetField(category.FieldThumbnail, field.TypeString, value)
		_node.Thumbnail = &value
	}
	if value, ok := _c.mutation.PostCount(); ok {
		_spec.SetField(category.FieldPostCount, field.TypeUint32, value)
		_node.PostCount = &value
	}
	if value, ok := _c.mutation.DirectPostCount(); ok {
		_spec.SetField(category.FieldDirectPostCount, field.TypeUint32, value)
		_node.DirectPostCount = &value
	}
	if value, ok := _c.mutation.Depth(); ok {
		_spec.SetField(category.FieldDepth, field.TypeInt32, value)
		_node.Depth = &value
	}
	if value, ok := _c.mutation.CustomFields(); ok {
		_spec.SetField(category.FieldCustomFields, field.TypeJSON, value)
		_node.CustomFields = value
	}
	if value, ok := _c.mutation.ContentModelID(); ok {
		_spec.SetField(category.FieldContentModelID, field.TypeUint32, value)
		_node.ContentModelID = &value
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   category.ParentTable,
			Columns: []string{category.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.ChildrenTable,
			Columns: []string{category.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Category.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CategoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CategoryCreate) OnConflict(opts ...sql.ConflictOption) *CategoryUpsertOne {
	_c.conflict = opts
	return &CategoryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Category.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CategoryCreate) OnConflictColumns(columns ...string) *CategoryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CategoryUpsertOne{
		create: _c,
	}
}

type (
	// CategoryUpsertOne is the builder for "upsert"-ing
	//  one Category node.
	CategoryUpsertOne struct {
		create *CategoryCreate
	}

	// CategoryUpsert is the "OnConflict" setter.
	CategoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CategoryUpsert) SetUpdatedAt(v time.Time) *CategoryUpsert {
	u.Set(category.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateUpdatedAt() *CategoryUpsert {
	u.SetExcluded(category.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CategoryUpsert) ClearUpdatedAt() *CategoryUpsert {
	u.SetNull(category.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CategoryUpsert) SetDeletedAt(v time.Time) *CategoryUpsert {
	u.Set(category.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateDeletedAt() *CategoryUpsert {
	u.SetExcluded(category.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CategoryUpsert) ClearDeletedAt() *CategoryUpsert {
	u.SetNull(category.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *CategoryUpsert) SetCreatedBy(v uint32) *CategoryUpsert {
	u.Set(category.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateCreatedBy() *CategoryUpsert {
	u.SetExcluded(category.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *CategoryUpsert) AddCreatedBy(v uint32) *CategoryUpsert {
	u.Add(category.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *CategoryUpsert) ClearCreatedBy() *CategoryUpsert {
	u.SetNull(category.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *CategoryUpsert) SetUpdatedBy(v uint32) *CategoryUpsert {
	u.Set(category.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateUpdatedBy() *CategoryUpsert {
	u.SetExcluded(category.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *CategoryUpsert) AddUpdatedBy(v uint32) *CategoryUpsert {
	u.Add(category.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *CategoryUpsert) ClearUpdatedBy() *CategoryUpsert {
	u.SetNull(category.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *CategoryUpsert) SetDeletedBy(v uint32) *CategoryUpsert {
	u.Set(category.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateDeletedBy() *CategoryUpsert {
	u.SetExcluded(category.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *CategoryUpsert) AddDeletedBy(v uint32) *CategoryUpsert {
	u.Add(category.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *CategoryUpsert) ClearDeletedBy() *CategoryUpsert {
	u.SetNull(category.FieldDeletedBy)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *CategoryUpsert) SetSortOrder(v uint32) *CategoryUpsert {
	u.Set(category.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateSortOrder() *CategoryUpsert {
	u.SetExcluded(category.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CategoryUpsert) AddSortOrder(v uint32) *CategoryUpsert {
	u.Add(category.FieldSortOrder, v)
	return u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (u *CategoryUpsert) ClearSortOrder() *CategoryUpsert {
	u.SetNull(category.FieldSortOrder)
	return u
}

// SetPath sets the "path" field.
func (u *CategoryUpsert) SetPath(v string) *CategoryUpsert {
	u.Set(category.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *CategoryUpsert) UpdatePath() *CategoryUpsert {
	u.SetExcluded(category.FieldPath)
	return u
}

// ClearPath clears the value of the "path" field.
func (u *CategoryUpsert) ClearPath() *CategoryUpsert {
	u.SetNull(category.FieldPath)
	return u
}

// SetParentID sets the "parent_id" field.
func (u *CategoryUpsert) SetParentID(v uint32) *CategoryUpsert {
	u.Set(category.FieldParentID, v)
	return u
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateParentID() *CategoryUpsert {
	u.SetExcluded(category.FieldParentID)
	return u
}

// ClearParentID clears the value of the "parent_id" field.
func (u *CategoryUpsert) ClearParentID() *CategoryUpsert {
	u.SetNull(category.FieldParentID)
	return u
}

// SetStatus sets the "status" field.
func (u *CategoryUpsert) SetStatus(v category.Status) *CategoryUpsert {
	u.Set(category.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateStatus() *CategoryUpsert {
	u.SetExcluded(category.FieldStatus)
	return u
}

// ClearStatus clears the value of the "status" field.
func (u *CategoryUpsert) ClearStatus() *CategoryUpsert {
	u.SetNull(category.FieldStatus)
	return u
}

// SetIsNav sets the "is_nav" field.
func (u *CategoryUpsert) SetIsNav(v bool) *CategoryUpsert {
	u.Set(category.FieldIsNav, v)
	return u
}

// UpdateIsNav sets the "is_nav" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateIsNav() *CategoryUpsert {
	u.SetExcluded(category.FieldIsNav)
	return u
}

// ClearIsNav clears the value of the "is_nav" field.
func (u *CategoryUpsert) ClearIsNav() *CategoryUpsert {
	u.SetNull(category.FieldIsNav)
	return u
}

// SetIcon sets the "icon" field.
func (u *CategoryUpsert) SetIcon(v string) *CategoryUpsert {
	u.Set(category.FieldIcon, v)
	return u
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateIcon() *CategoryUpsert {
	u.SetExcluded(category.FieldIcon)
	return u
}

// ClearIcon clears the value of the "icon" field.
func (u *CategoryUpsert) ClearIcon() *CategoryUpsert {
	u.SetNull(category.FieldIcon)
	return u
}

// SetCode sets the "code" field.
func (u *CategoryUpsert) SetCode(v string) *CategoryUpsert {
	u.Set(category.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateCode() *CategoryUpsert {
	u.SetExcluded(category.FieldCode)
	return u
}

// ClearCode clears the value of the "code" field.
func (u *CategoryUpsert) ClearCode() *CategoryUpsert {
	u.SetNull(category.FieldCode)
	return u
}

// SetThumbnail sets the "thumbnail" field.
func (u *CategoryUpsert) SetThumbnail(v string) *CategoryUpsert {
	u.Set(category.FieldThumbnail, v)
	return u
}

// UpdateThumbnail sets the "thumbnail" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateThumbnail() *CategoryUpsert {
	u.SetExcluded(category.FieldThumbnail)
	return u
}

// ClearThumbnail clears the value of the "thumbnail" field.
func (u *CategoryUpsert) ClearThumbnail() *CategoryUpsert {
	u.SetNull(category.FieldThumbnail)
	return u
}

// SetPostCount sets the "post_count" field.
func (u *CategoryUpsert) SetPostCount(v uint32) *CategoryUpsert {
	u.Set(category.FieldPostCount, v)
	return u
}

// UpdatePostCount sets the "post_count" field to the value that was provided on create.
func (u *CategoryUpsert) UpdatePostCount() *CategoryUpsert {
	u.SetExcluded(category.FieldPostCount)
	return u
}

// AddPostCount adds v to the "post_count" field.
func (u *CategoryUpsert) AddPostCount(v uint32) *CategoryUpsert {
	u.Add(category.FieldPostCount, v)
	return u
}

// ClearPostCount clears the value of the "post_count" field.
func (u *CategoryUpsert) ClearPostCount() *CategoryUpsert {
	u.SetNull(category.FieldPostCount)
	return u
}

// SetDirectPostCount sets the "direct_post_count" field.
func (u *CategoryUpsert) SetDirectPostCount(v uint32) *CategoryUpsert {
	u.Set(category.FieldDirectPostCount, v)
	return u
}

// UpdateDirectPostCount sets the "direct_post_count" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateDirectPostCount() *CategoryUpsert {
	u.SetExcluded(category.FieldDirectPostCount)
	return u
}

// AddDirectPostCount adds v to the "direct_post_count" field.
func (u *CategoryUpsert) AddDirectPostCount(v uint32) *CategoryUpsert {
	u.Add(category.FieldDirectPostCount, v)
	return u
}

// ClearDirectPostCount clears the value of the "direct_post_count" field.
func (u *CategoryUpsert) ClearDirectPostCount() *CategoryUpsert {
	u.SetNull(category.FieldDirectPostCount)
	return u
}

// SetDepth sets the "depth" field.
func (u *CategoryUpsert) SetDepth(v int32) *CategoryUpsert {
	u.Set(category.FieldDepth, v)
	return u
}

// UpdateDepth sets the "depth" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateDepth() *CategoryUpsert {
	u.SetExcluded(category.FieldDepth)
	return u
}

// AddDepth adds v to the "depth" field.
func (u *CategoryUpsert) AddDepth(v int32) *CategoryUpsert {
	u.Add(category.FieldDepth, v)
	return u
}

// ClearDepth clears the value of the "depth" field.
func (u *CategoryUpsert) ClearDepth() *CategoryUpsert {
	u.SetNull(category.FieldDepth)
	return u
}

// SetCustomFields sets the "custom_fields" field.
func (u *CategoryUpsert) SetCustomFields(v *map[string]string) *CategoryUpsert {
	u.Set(category.FieldCustomFields, v)
	return u
}

// UpdateCustomFields sets the "custom_fields" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateCustomFields() *CategoryUpsert {
	u.SetExcluded(category.FieldCustomFields)
	return u
}

// ClearCustomFields clears the value of the "custom_fields" field.
func (u *CategoryUpsert) ClearCustomFields() *CategoryUpsert {
	u.SetNull(category.FieldCustomFields)
	return u
}

// SetContentModelID sets the "content_model_id" field.
func (u *CategoryUpsert) SetContentModelID(v uint32) *CategoryUpsert {
	u.Set(category.FieldContentModelID, v)
	return u
}

// UpdateContentModelID sets the "content_model_id" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateContentModelID() *CategoryUpsert {
	u.SetExcluded(category.FieldContentModelID)
	return u
}

// AddContentModelID adds v to the "content_model_id" field.
func (u *CategoryUpsert) AddContentModelID(v uint32) *CategoryUpsert {
	u.Add(category.FieldContentModelID, v)
	return u
}

// ClearContentModelID clears the value of the "content_model_id" field.
func (u *CategoryUpsert) ClearContentModelID() *CategoryUpsert {
	u.SetNull(category.FieldContentModelID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Category.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(category.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CategoryUpsertOne) UpdateNewValues() *CategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(category.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(category.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(category.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Category.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CategoryUpsertOne) Ignore() *CategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CategoryUpsertOne) DoNothing() *CategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CategoryCreate.OnConflict
// documentation for more info.
func (u *CategoryUpsertOne) Update(set func(*CategoryUpsert)) *CategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CategoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CategoryUpsertOne) SetUpdatedAt(v time.Time) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateUpdatedAt() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CategoryUpsertOne) ClearUpdatedAt() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CategoryUpsertOne) SetDeletedAt(v time.Time) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateDeletedAt() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CategoryUpsertOne) ClearDeletedAt() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *CategoryUpsertOne) SetCreatedBy(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *CategoryUpsertOne) AddCreatedBy(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateCreatedBy() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *CategoryUpsertOne) ClearCreatedBy() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *CategoryUpsertOne) SetUpdatedBy(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *CategoryUpsertOne) AddUpdatedBy(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateUpdatedBy() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *CategoryUpsertOne) ClearUpdatedBy() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *CategoryUpsertOne) SetDeletedBy(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *CategoryUpsertOne) AddDeletedBy(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateDeletedBy() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *CategoryUpsertOne) ClearDeletedBy() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearDeletedBy()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *CategoryUpsertOne) SetSortOrder(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CategoryUpsertOne) AddSortOrder(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateSortOrder() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateSortOrder()
	})
}

// ClearSortOrder clears the value of the "sort_order" field.
func (u *CategoryUpsertOne) ClearSortOrder() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearSortOrder()
	})
}

// SetPath sets the "path" field.
func (u *CategoryUpsertOne) SetPath(v string) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdatePath() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdatePath()
	})
}

// ClearPath clears the value of the "path" field.
func (u *CategoryUpsertOne) ClearPath() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearPath()
	})
}

// SetParentID sets the "parent_id" field.
func (u *CategoryUpsertOne) SetParentID(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateParentID() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *CategoryUpsertOne) ClearParentID() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearParentID()
	})
}

// SetStatus sets the "status" field.
func (u *CategoryUpsertOne) SetStatus(v category.Status) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateStatus() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *CategoryUpsertOne) ClearStatus() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearStatus()
	})
}

// SetIsNav sets the "is_nav" field.
func (u *CategoryUpsertOne) SetIsNav(v bool) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetIsNav(v)
	})
}

// UpdateIsNav sets the "is_nav" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateIsNav() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateIsNav()
	})
}

// ClearIsNav clears the value of the "is_nav" field.
func (u *CategoryUpsertOne) ClearIsNav() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearIsNav()
	})
}

// SetIcon sets the "icon" field.
func (u *CategoryUpsertOne) SetIcon(v string) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateIcon() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateIcon()
	})
}

// ClearIcon clears the value of the "icon" field.
func (u *CategoryUpsertOne) ClearIcon() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearIcon()
	})
}

// SetCode sets the "code" field.
func (u *CategoryUpsertOne) SetCode(v string) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateCode() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *CategoryUpsertOne) ClearCode() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearCode()
	})
}

// SetThumbnail sets the "thumbnail" field.
func (u *CategoryUpsertOne) SetThumbnail(v string) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetThumbnail(v)
	})
}

// UpdateThumbnail sets the "thumbnail" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateThumbnail() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateThumbnail()
	})
}

// ClearThumbnail clears the value of the "thumbnail" field.
func (u *CategoryUpsertOne) ClearThumbnail() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearThumbnail()
	})
}

// SetPostCount sets the "post_count" field.
func (u *CategoryUpsertOne) SetPostCount(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetPostCount(v)
	})
}

// AddPostCount adds v to the "post_count" field.
func (u *CategoryUpsertOne) AddPostCount(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.AddPostCount(v)
	})
}

// UpdatePostCount sets the "post_count" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdatePostCount() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdatePostCount()
	})
}

// ClearPostCount clears the value of the "post_count" field.
func (u *CategoryUpsertOne) ClearPostCount() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearPostCount()
	})
}

// SetDirectPostCount sets the "direct_post_count" field.
func (u *CategoryUpsertOne) SetDirectPostCount(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetDirectPostCount(v)
	})
}

// AddDirectPostCount adds v to the "direct_post_count" field.
func (u *CategoryUpsertOne) AddDirectPostCount(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.AddDirectPostCount(v)
	})
}

// UpdateDirectPostCount sets the "direct_post_count" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateDirectPostCount() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateDirectPostCount()
	})
}

// ClearDirectPostCount clears the value of the "direct_post_count" field.
func (u *CategoryUpsertOne) ClearDirectPostCount() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearDirectPostCount()
	})
}

// SetDepth sets the "depth" field.
func (u *CategoryUpsertOne) SetDepth(v int32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetDepth(v)
	})
}

// AddDepth adds v to the "depth" field.
func (u *CategoryUpsertOne) AddDepth(v int32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.AddDepth(v)
	})
}

// UpdateDepth sets the "depth" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateDepth() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateDepth()
	})
}

// ClearDepth clears the value of the "depth" field.
func (u *CategoryUpsertOne) ClearDepth() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearDepth()
	})
}

// SetCustomFields sets the "custom_fields" field.
func (u *CategoryUpsertOne) SetCustomFields(v *map[string]string) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetCustomFields(v)
	})
}

// UpdateCustomFields sets the "custom_fields" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateCustomFields() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateCustomFields()
	})
}

// ClearCustomFields clears the value of the "custom_fields" field.
func (u *CategoryUpsertOne) ClearCustomFields() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearCustomFields()
	})
}

// SetContentModelID sets the "content_model_id" field.
func (u *CategoryUpsertOne) SetContentModelID(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetContentModelID(v)
	})
}

// AddContentModelID adds v to the "content_model_id" field.
func (u *CategoryUpsertOne) AddContentModelID(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.AddContentModelID(v)
	})
}

// UpdateContentModelID sets the "content_model_id" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateContentModelID() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateContentModelID()
	})
}

// ClearContentModelID clears the value of the "content_model_id" field.
func (u *CategoryUpsertOne) ClearContentModelID() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearContentModelID()
	})
}

// Exec executes the query.
func (u *CategoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CategoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CategoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CategoryUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CategoryUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CategoryCreateBulk is the builder for creating many Category entities in bulk.
type CategoryCreateBulk struct {
	config
	err      error
	builders []*CategoryCreate
	conflict []sql.ConflictOption
}

// Save creates the Category entities in the database.
func (_c *CategoryCreateBulk) Save(ctx context.Context) ([]*Category, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Category, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CategoryCreateBulk) SaveX(ctx context.Context) []*Category {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CategoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Category.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CategoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CategoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *CategoryUpsertBulk {
	_c.conflict = opts
	return &CategoryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Category.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CategoryCreateBulk) OnConflictColumns(columns ...string) *CategoryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CategoryUpsertBulk{
		create: _c,
	}
}

// CategoryUpsertBulk is the builder for "upsert"-ing
// a bulk of Category nodes.
type CategoryUpsertBulk struct {
	create *CategoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Category.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(category.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CategoryUpsertBulk) UpdateNewValues() *CategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(category.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(category.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(category.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Category.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CategoryUpsertBulk) Ignore() *CategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CategoryUpsertBulk) DoNothing() *CategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CategoryCreateBulk.OnConflict
// documentation for more info.
func (u *CategoryUpsertBulk) Update(set func(*CategoryUpsert)) *CategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CategoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CategoryUpsertBulk) SetUpdatedAt(v time.Time) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateUpdatedAt() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *CategoryUpsertBulk) ClearUpdatedAt() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CategoryUpsertBulk) SetDeletedAt(v time.Time) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateDeletedAt() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CategoryUpsertBulk) ClearDeletedAt() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *CategoryUpsertBulk) SetCreatedBy(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *CategoryUpsertBulk) AddCreatedBy(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateCreatedBy() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *CategoryUpsertBulk) ClearCreatedBy() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *CategoryUpsertBulk) SetUpdatedBy(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *CategoryUpsertBulk) AddUpdatedBy(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateUpdatedBy() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *CategoryUpsertBulk) ClearUpdatedBy() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *CategoryUpsertBulk) SetDeletedBy(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *CategoryUpsertBulk) AddDeletedBy(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateDeletedBy() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *CategoryUpsertBulk) ClearDeletedBy() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearDeletedBy()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *CategoryUpsertBulk) SetSortOrder(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CategoryUpsertBulk) AddSortOrder(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateSortOrder() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateSortOrder()
	})
}

// ClearSortOrder clears the value of the "sort_order" field.
func (u *CategoryUpsertBulk) ClearSortOrder() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearSortOrder()
	})
}

// SetPath sets the "path" field.
func (u *CategoryUpsertBulk) SetPath(v string) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdatePath() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdatePath()
	})
}

// ClearPath clears the value of the "path" field.
func (u *CategoryUpsertBulk) ClearPath() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearPath()
	})
}

// SetParentID sets the "parent_id" field.
func (u *CategoryUpsertBulk) SetParentID(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateParentID() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *CategoryUpsertBulk) ClearParentID() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearParentID()
	})
}

// SetStatus sets the "status" field.
func (u *CategoryUpsertBulk) SetStatus(v category.Status) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateStatus() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *CategoryUpsertBulk) ClearStatus() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearStatus()
	})
}

// SetIsNav sets the "is_nav" field.
func (u *CategoryUpsertBulk) SetIsNav(v bool) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetIsNav(v)
	})
}

// UpdateIsNav sets the "is_nav" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateIsNav() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateIsNav()
	})
}

// ClearIsNav clears the value of the "is_nav" field.
func (u *CategoryUpsertBulk) ClearIsNav() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearIsNav()
	})
}

// SetIcon sets the "icon" field.
func (u *CategoryUpsertBulk) SetIcon(v string) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateIcon() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateIcon()
	})
}

// ClearIcon clears the value of the "icon" field.
func (u *CategoryUpsertBulk) ClearIcon() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearIcon()
	})
}

// SetCode sets the "code" field.
func (u *CategoryUpsertBulk) SetCode(v string) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateCode() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *CategoryUpsertBulk) ClearCode() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearCode()
	})
}

// SetThumbnail sets the "thumbnail" field.
func (u *CategoryUpsertBulk) SetThumbnail(v string) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetThumbnail(v)
	})
}

// UpdateThumbnail sets the "thumbnail" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateThumbnail() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateThumbnail()
	})
}

// ClearThumbnail clears the value of the "thumbnail" field.
func (u *CategoryUpsertBulk) ClearThumbnail() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearThumbnail()
	})
}

// SetPostCount sets the "post_count" field.
func (u *CategoryUpsertBulk) SetPostCount(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetPostCount(v)
	})
}

// AddPostCount adds v to the "post_count" field.
func (u *CategoryUpsertBulk) AddPostCount(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.AddPostCount(v)
	})
}

// UpdatePostCount sets the "post_count" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdatePostCount() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdatePostCount()
	})
}

// ClearPostCount clears the value of the "post_count" field.
func (u *CategoryUpsertBulk) ClearPostCount() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearPostCount()
	})
}

// SetDirectPostCount sets the "direct_post_count" field.
func (u *CategoryUpsertBulk) SetDirectPostCount(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetDirectPostCount(v)
	})
}

// AddDirectPostCount adds v to the "direct_post_count" field.
func (u *CategoryUpsertBulk) AddDirectPostCount(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.AddDirectPostCount(v)
	})
}

// UpdateDirectPostCount sets the "direct_post_count" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateDirectPostCount() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateDirectPostCount()
	})
}

// ClearDirectPostCount clears the value of the "direct_post_count" field.
func (u *CategoryUpsertBulk) ClearDirectPostCount() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearDirectPostCount()
	})
}

// SetDepth sets the "depth" field.
func (u *CategoryUpsertBulk) SetDepth(v int32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetDepth(v)
	})
}

// AddDepth adds v to the "depth" field.
func (u *CategoryUpsertBulk) AddDepth(v int32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.AddDepth(v)
	})
}

// UpdateDepth sets the "depth" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateDepth() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateDepth()
	})
}

// ClearDepth clears the value of the "depth" field.
func (u *CategoryUpsertBulk) ClearDepth() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearDepth()
	})
}

// SetCustomFields sets the "custom_fields" field.
func (u *CategoryUpsertBulk) SetCustomFields(v *map[string]string) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetCustomFields(v)
	})
}

// UpdateCustomFields sets the "custom_fields" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateCustomFields() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateCustomFields()
	})
}

// ClearCustomFields clears the value of the "custom_fields" field.
func (u *CategoryUpsertBulk) ClearCustomFields() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearCustomFields()
	})
}

// SetContentModelID sets the "content_model_id" field.
func (u *CategoryUpsertBulk) SetContentModelID(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetContentModelID(v)
	})
}

// AddContentModelID adds v to the "content_model_id" field.
func (u *CategoryUpsertBulk) AddContentModelID(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.AddContentModelID(v)
	})
}

// UpdateContentModelID sets the "content_model_id" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateContentModelID() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateContentModelID()
	})
}

// ClearContentModelID clears the value of the "content_model_id" field.
func (u *CategoryUpsertBulk) ClearContentModelID() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearContentModelID()
	})
}

// Exec executes the query.
func (u *CategoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CategoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CategoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CategoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
