// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	contentpb "go-wind-cms/api/gen/go/content/service/v1"
	"go-wind-cms/app/core/service/internal/data/ent/posttranslation"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostTranslationCreate is the builder for creating a PostTranslation entity.
type PostTranslationCreate struct {
	config
	mutation *PostTranslationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PostTranslationCreate) SetCreatedAt(v time.Time) *PostTranslationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PostTranslationCreate) SetNillableCreatedAt(v *time.Time) *PostTranslationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PostTranslationCreate) SetUpdatedAt(v time.Time) *PostTranslationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PostTranslationCreate) SetNillableUpdatedAt(v *time.Time) *PostTranslationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *PostTranslationCreate) SetDeletedAt(v time.Time) *PostTranslationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *PostTranslationCreate) SetNillableDeletedAt(v *time.Time) *PostTranslationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *PostTranslationCreate) SetCreatedBy(v uint32) *PostTranslationCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *PostTranslationCreate) SetNillableCreatedBy(v *uint32) *PostTranslationCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *PostTranslationCreate) SetUpdatedBy(v uint32) *PostTranslationCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *PostTranslationCreate) SetNillableUpdatedBy(v *uint32) *PostTranslationCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *PostTranslationCreate) SetDeletedBy(v uint32) *PostTranslationCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *PostTranslationCreate) SetNillableDeletedBy(v *uint32) *PostTranslationCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetSeo sets the "seo" field.
func (_c *PostTranslationCreate) SetSeo(v *contentpb.SeoMeta) *PostTranslationCreate {
	_c.mutation.SetSeo(v)
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *PostTranslationCreate) SetTenantID(v uint32) *PostTranslationCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *PostTranslationCreate) SetNillableTenantID(v *uint32) *PostTranslationCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetPostID sets the "post_id" field.
func (_c *PostTranslationCreate) SetPostID(v uint32) *PostTranslationCreate {
	_c.mutation.SetPostID(v)
	return _c
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_c *PostTranslationCreate) SetNillablePostID(v *uint32) *PostTranslationCreate {
	if v != nil {
		_c.SetPostID(*v)
	}
	return _c
}

// SetLanguageCode sets the "language_code" field.
func (_c *PostTranslationCreate) SetLanguageCode(v string) *PostTranslationCreate {
	_c.mutation.SetLanguageCode(v)
	return _c
}

// SetNillableLanguageCode sets the "language_code" field if the given value is not nil.
func (_c *PostTranslationCreate) SetNillableLanguageCode(v *string) *PostTranslationCreate {
	if v != nil {
		_c.SetLanguageCode(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *PostTranslationCreate) SetTitle(v string) *PostTranslationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *PostTranslationCreate) SetNillableTitle(v *string) *PostTranslationCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetSlug sets the "slug" field.
func (_c *PostTranslationCreate) SetSlug(v string) *PostTranslationCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_c *PostTranslationCreate) SetNillableSlug(v *string) *PostTranslationCreate {
	if v != nil {
		_c.SetSlug(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *PostTranslationCreate) SetSummary(v string) *PostTranslationCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *PostTranslationCreate) SetNillableSummary(v *string) *PostTranslationCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *PostTranslationCreate) SetContent(v string) *PostTranslationCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *PostTranslationCreate) SetNillableContent(v *string) *PostTranslationCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetOriginalContent sets the "original_content" field.
func (_c *PostTranslationCreate) SetOriginalContent(v string) *PostTranslationCreate {
	_c.mutation.SetOriginalContent(v)
	return _c
}

// SetNillableOriginalContent sets the "original_content" field if the given value is not nil.
func (_c *PostTranslationCreate) SetNillableOriginalContent(v *string) *PostTranslationCreate {
	if v != nil {
		_c.SetOriginalContent(*v)
	}
	return _c
}

// SetFullPath sets the "full_path" field.
func (_c *PostTranslationCreate) SetFullPath(v string) *PostTranslationCreate {
	_c.mutation.SetFullPath(v)
	return _c
}

// SetNillableFullPath sets the "full_path" field if the given value is not nil.
func (_c *PostTranslationCreate) SetNillableFullPath(v *string) *PostTranslationCreate {
	if v != nil {
		_c.SetFullPath(*v)
	}
	return _c
}

// SetWordCount sets the "word_count" field.
func (_c *PostTranslationCreate) SetWordCount(v uint32) *PostTranslationCreate {
	_c.mutation.SetWordCount(v)
	return _c
}

// SetNillableWordCount sets the "word_count" field if the given value is not nil.
func (_c *PostTranslationCreate) SetNillableWordCount(v *uint32) *PostTranslationCreate {
	if v != nil {
		_c.SetWordCount(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PostTranslationCreate) SetID(v uint32) *PostTranslationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PostTranslationMutation object of the builder.
func (_c *PostTranslationCreate) Mutation() *PostTranslationMutation {
	return _c.mutation
}

// Save creates the PostTranslation in the database.
func (_c *PostTranslationCreate) Save(ctx context.Context) (*PostTranslation, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PostTranslationCreate) SaveX(ctx context.Context) *PostTranslation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostTranslationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostTranslationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PostTranslationCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := posttranslation.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.WordCount(); !ok {
		v := posttranslation.DefaultWordCount
		_c.mutation.SetWordCount(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *PostTranslationCreate) check() error {
	if v, ok := _c.mutation.Seo(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "seo", err: fmt.Errorf(`ent: validator failed for field "PostTranslation.seo": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := posttranslation.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "PostTranslation.id": %w`, err)}
		}
	}
	return nil
}

func (_c *PostTranslationCreate) sqlSave(ctx context.Context) (*PostTranslation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PostTranslationCreate) createSpec() (*PostTranslation, *sqlgraph.CreateSpec) {
	var (
		_node = &PostTranslation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(posttranslation.Table, sqlgraph.NewFieldSpec(posttranslation.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(posttranslation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(posttranslation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(posttranslation.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(posttranslation.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(posttranslation.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(posttranslation.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.Seo(); ok {
		_spec.SetField(posttranslation.FieldSeo, field.TypeJSON, value)
		_node.Seo = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(posttranslation.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.PostID(); ok {
		_spec.SetField(posttranslation.FieldPostID, field.TypeUint32, value)
		_node.PostID = &value
	}
	if value, ok := _c.mutation.LanguageCode(); ok {
		_spec.SetField(posttranslation.FieldLanguageCode, field.TypeString, value)
		_node.LanguageCode = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(posttranslation.FieldTitle, field.TypeString, value)
		_node.Title = &value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(posttranslation.FieldSlug, field.TypeString, value)
		_node.Slug = &value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(posttranslation.FieldSummary, field.TypeString, value)
		_node.Summary = &value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(posttranslation.FieldContent, field.TypeString, value)
		_node.Content = &value
	}
	if value, ok := _c.mutation.OriginalContent(); ok {
		_spec.SetField(posttranslation.FieldOriginalContent, field.TypeString, value)
		_node.OriginalContent = &value
	}
	if value, ok := _c.mutation.FullPath(); ok {
		_spec.SetField(posttranslation.FieldFullPath, field.TypeString, value)
		_node.FullPath = &value
	}
	if value, ok := _c.mutation.WordCount(); ok {
		_spec.SetField(posttranslation.FieldWordCount, field.TypeUint32, value)
		_node.WordCount = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PostTranslation.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PostTranslationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PostTranslationCreate) OnConflict(opts ...sql.ConflictOption) *PostTranslationUpsertOne {
	_c.conflict = opts
	return &PostTranslationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PostTranslation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PostTranslationCreate) OnConflictColumns(columns ...string) *PostTranslationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PostTranslationUpsertOne{
		create: _c,
	}
}

type (
	// PostTranslationUpsertOne is the builder for "upsert"-ing
	//  one PostTranslation node.
	PostTranslationUpsertOne struct {
		create *PostTranslationCreate
	}

	// PostTranslationUpsert is the "OnConflict" setter.
	PostTranslationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PostTranslationUpsert) SetUpdatedAt(v time.Time) *PostTranslationUpsert {
	u.Set(posttranslation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PostTranslationUpsert) UpdateUpdatedAt() *PostTranslationUpsert {
	u.SetExcluded(posttranslation.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *PostTranslationUpsert) ClearUpdatedAt() *PostTranslationUpsert {
	u.SetNull(posttranslation.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PostTranslationUpsert) SetDeletedAt(v time.Time) *PostTranslationUpsert {
	u.Set(posttranslation.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PostTranslationUpsert) UpdateDeletedAt() *PostTranslationUpsert {
	u.SetExcluded(posttranslation.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PostTranslationUpsert) ClearDeletedAt() *PostTranslationUpsert {
	u.SetNull(posttranslation.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *PostTranslationUpsert) SetCreatedBy(v uint32) *PostTranslationUpsert {
	u.Set(posttranslation.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *PostTranslationUpsert) UpdateCreatedBy() *PostTranslationUpsert {
	u.SetExcluded(posttranslation.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *PostTranslationUpsert) AddCreatedBy(v uint32) *PostTranslationUpsert {
	u.Add(posttranslation.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *PostTranslationUpsert) ClearCreatedBy() *PostTranslationUpsert {
	u.SetNull(posttranslation.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PostTranslationUpsert) SetUpdatedBy(v uint32) *PostTranslationUpsert {
	u.Set(posttranslation.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PostTranslationUpsert) UpdateUpdatedBy() *PostTranslationUpsert {
	u.SetExcluded(posttranslation.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PostTranslationUpsert) AddUpdatedBy(v uint32) *PostTranslationUpsert {
	u.Add(posttranslation.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PostTranslationUpsert) ClearUpdatedBy() *PostTranslationUpsert {
	u.SetNull(posttranslation.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *PostTranslationUpsert) SetDeletedBy(v uint32) *PostTranslationUpsert {
	u.Set(posttranslation.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *PostTranslationUpsert) UpdateDeletedBy() *PostTranslationUpsert {
	u.SetExcluded(posttranslation.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *PostTranslationUpsert) AddDeletedBy(v uint32) *PostTranslationUpsert {
	u.Add(posttranslation.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *PostTranslationUpsert) ClearDeletedBy() *PostTranslationUpsert {
	u.SetNull(posttranslation.FieldDeletedBy)
	return u
}

// SetSeo sets the "seo" field.
func (u *PostTranslationUpsert) SetSeo(v *contentpb.SeoMeta) *PostTranslationUpsert {
	u.Set(posttranslation.FieldSeo, v)
	return u
}

// UpdateSeo sets the "seo" field to the value that was provided on create.
func (u *PostTranslationUpsert) UpdateSeo() *PostTranslationUpsert {
	u.SetExcluded(posttranslation.FieldSeo)
	return u
}

// ClearSeo clears the value of the "seo" field.
func (u *PostTranslationUpsert) ClearSeo() *PostTranslationUpsert {
	u.SetNull(posttranslation.FieldSeo)
	return u
}

// SetPostID sets the "post_id" field.
func (u *PostTranslationUpsert) SetPostID(v uint32) *PostTranslationUpsert {
	u.Set(posttranslation.FieldPostID, v)
	return u
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *PostTranslationUpsert) UpdatePostID() *PostTranslationUpsert {
	u.SetExcluded(posttranslation.FieldPostID)
	return u
}

// AddPostID adds v to the "post_id" field.
func (u *PostTranslationUpsert) AddPostID(v uint32) *PostTranslationUpsert {
	u.Add(posttranslation.FieldPostID, v)
	return u
}

// ClearPostID clears the value of the "post_id" field.
func (u *PostTranslationUpsert) ClearPostID() *PostTranslationUpsert {
	u.SetNull(posttranslation.FieldPostID)
	return u
}

// SetLanguageCode sets the "language_code" field.
func (u *PostTranslationUpsert) SetLanguageCode(v string) *PostTranslationUpsert {
	u.Set(posttranslation.FieldLanguageCode, v)
	return u
}

// UpdateLanguageCode sets the "language_code" field to the value that was provided on create.
func (u *PostTranslationUpsert) UpdateLanguageCode() *PostTranslationUpsert {
	u.SetExcluded(posttranslation.FieldLanguageCode)
	return u
}

// ClearLanguageCode clears the value of the "language_code" field.
func (u *PostTranslationUpsert) ClearLanguageCode() *PostTranslationUpsert {
	u.SetNull(posttranslation.FieldLanguageCode)
	return u
}

// SetTitle sets the "title" field.
func (u *PostTranslationUpsert) SetTitle(v string) *PostTranslationUpsert {
	u.Set(posttranslation.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PostTranslationUpsert) UpdateTitle() *PostTranslationUpsert {
	u.SetExcluded(posttranslation.FieldTitle)
	return u
}

// ClearTitle clears the value of the "title" field.
func (u *PostTranslationUpsert) ClearTitle() *PostTranslationUpsert {
	u.SetNull(posttranslation.FieldTitle)
	return u
}

// SetSlug sets the "slug" field.
func (u *PostTranslationUpsert) SetSlug(v string) *PostTranslationUpsert {
	u.Set(posttranslation.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *PostTranslationUpsert) UpdateSlug() *PostTranslationUpsert {
	u.SetExcluded(posttranslation.FieldSlug)
	return u
}

// ClearSlug clears the value of the "slug" field.
func (u *PostTranslationUpsert) ClearSlug() *PostTranslationUpsert {
	u.SetNull(posttranslation.FieldSlug)
	return u
}

// SetSummary sets the "summary" field.
func (u *PostTranslationUpsert) SetSummary(v string) *PostTranslationUpsert {
	u.Set(posttranslation.FieldSummary, v)
	return u
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *PostTranslationUpsert) UpdateSummary() *PostTranslationUpsert {
	u.SetExcluded(posttranslation.FieldSummary)
	return u
}

// ClearSummary clears the value of the "summary" field.
func (u *PostTranslationUpsert) ClearSummary() *PostTranslationUpsert {
	u.SetNull(posttranslation.FieldSummary)
	return u
}

// SetContent sets the "content" field.
func (u *PostTranslationUpsert) SetContent(v string) *PostTranslationUpsert {
	u.Set(posttranslation.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *PostTranslationUpsert) UpdateContent() *PostTranslationUpsert {
	u.SetExcluded(posttranslation.FieldContent)
	return u
}

// ClearContent clears the value of the "content" field.
func (u *PostTranslationUpsert) ClearContent() *PostTranslationUpsert {
	u.SetNull(posttranslation.FieldContent)
	return u
}

// SetOriginalContent sets the "original_content" field.
func (u *PostTranslationUpsert) SetOriginalContent(v string) *PostTranslationUpsert {
	u.Set(posttranslation.FieldOriginalContent, v)
	return u
}

// UpdateOriginalContent sets the "original_content" field to the value that was provided on create.
func (u *PostTranslationUpsert) UpdateOriginalContent() *PostTranslationUpsert {
	u.SetExcluded(posttranslation.FieldOriginalContent)
	return u
}

// ClearOriginalContent clears the value of the "original_content" field.
func (u *PostTranslationUpsert) ClearOriginalContent() *PostTranslationUpsert {
	u.SetNull(posttranslation.FieldOriginalContent)
	return u
}

// SetFullPath sets the "full_path" field.
func (u *PostTranslationUpsert) SetFullPath(v string) *PostTranslationUpsert {
	u.Set(posttranslation.FieldFullPath, v)
	return u
}

// UpdateFullPath sets the "full_path" field to the value that was provided on create.
func (u *PostTranslationUpsert) UpdateFullPath() *PostTranslationUpsert {
	u.SetExcluded(posttranslation.FieldFullPath)
	return u
}

// ClearFullPath clears the value of the "full_path" field.
func (u *PostTranslationUpsert) ClearFullPath() *PostTranslationUpsert {
	u.SetNull(posttranslation.FieldFullPath)
	return u
}

// SetWordCount sets the "word_count" field.
func (u *PostTranslationUpsert) SetWordCount(v uint32) *PostTranslationUpsert {
	u.Set(posttranslation.FieldWordCount, v)
	return u
}

// UpdateWordCount sets the "word_count" field to the value that was provided on create.
func (u *PostTranslationUpsert) UpdateWordCount() *PostTranslationUpsert {
	u.SetExcluded(posttranslation.FieldWordCount)
	return u
}

// AddWordCount adds v to the "word_count" field.
func (u *PostTranslationUpsert) AddWordCount(v uint32) *PostTranslationUpsert {
	u.Add(posttranslation.FieldWordCount, v)
	return u
}

// ClearWordCount clears the value of the "word_count" field.
func (u *PostTranslationUpsert) ClearWordCount() *PostTranslationUpsert {
	u.SetNull(posttranslation.FieldWordCount)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PostTranslation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(posttranslation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PostTranslationUpsertOne) UpdateNewValues() *PostTranslationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(posttranslation.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(posttranslation.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(posttranslation.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PostTranslation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PostTranslationUpsertOne) Ignore() *PostTranslationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PostTranslationUpsertOne) DoNothing() *PostTranslationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PostTranslationCreate.OnConflict
// documentation for more info.
func (u *PostTranslationUpsertOne) Update(set func(*PostTranslationUpsert)) *PostTranslationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PostTranslationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PostTranslationUpsertOne) SetUpdatedAt(v time.Time) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PostTranslationUpsertOne) UpdateUpdatedAt() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *PostTranslationUpsertOne) ClearUpdatedAt() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PostTranslationUpsertOne) SetDeletedAt(v time.Time) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PostTranslationUpsertOne) UpdateDeletedAt() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PostTranslationUpsertOne) ClearDeletedAt() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *PostTranslationUpsertOne) SetCreatedBy(v uint32) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *PostTranslationUpsertOne) AddCreatedBy(v uint32) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *PostTranslationUpsertOne) UpdateCreatedBy() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *PostTranslationUpsertOne) ClearCreatedBy() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PostTranslationUpsertOne) SetUpdatedBy(v uint32) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PostTranslationUpsertOne) AddUpdatedBy(v uint32) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PostTranslationUpsertOne) UpdateUpdatedBy() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PostTranslationUpsertOne) ClearUpdatedBy() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *PostTranslationUpsertOne) SetDeletedBy(v uint32) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *PostTranslationUpsertOne) AddDeletedBy(v uint32) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *PostTranslationUpsertOne) UpdateDeletedBy() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *PostTranslationUpsertOne) ClearDeletedBy() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearDeletedBy()
	})
}

// SetSeo sets the "seo" field.
func (u *PostTranslationUpsertOne) SetSeo(v *contentpb.SeoMeta) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetSeo(v)
	})
}

// UpdateSeo sets the "seo" field to the value that was provided on create.
func (u *PostTranslationUpsertOne) UpdateSeo() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateSeo()
	})
}

// ClearSeo clears the value of the "seo" field.
func (u *PostTranslationUpsertOne) ClearSeo() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearSeo()
	})
}

// SetPostID sets the "post_id" field.
func (u *PostTranslationUpsertOne) SetPostID(v uint32) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetPostID(v)
	})
}

// AddPostID adds v to the "post_id" field.
func (u *PostTranslationUpsertOne) AddPostID(v uint32) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.AddPostID(v)
	})
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *PostTranslationUpsertOne) UpdatePostID() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdatePostID()
	})
}

// ClearPostID clears the value of the "post_id" field.
func (u *PostTranslationUpsertOne) ClearPostID() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearPostID()
	})
}

// SetLanguageCode sets the "language_code" field.
func (u *PostTranslationUpsertOne) SetLanguageCode(v string) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetLanguageCode(v)
	})
}

// UpdateLanguageCode sets the "language_code" field to the value that was provided on create.
func (u *PostTranslationUpsertOne) UpdateLanguageCode() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateLanguageCode()
	})
}

// ClearLanguageCode clears the value of the "language_code" field.
func (u *PostTranslationUpsertOne) ClearLanguageCode() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearLanguageCode()
	})
}

// SetTitle sets the "title" field.
func (u *PostTranslationUpsertOne) SetTitle(v string) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PostTranslationUpsertOne) UpdateTitle() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *PostTranslationUpsertOne) ClearTitle() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearTitle()
	})
}

// SetSlug sets the "slug" field.
func (u *PostTranslationUpsertOne) SetSlug(v string) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *PostTranslationUpsertOne) UpdateSlug() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateSlug()
	})
}

// ClearSlug clears the value of the "slug" field.
func (u *PostTranslationUpsertOne) ClearSlug() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearSlug()
	})
}

// SetSummary sets the "summary" field.
func (u *PostTranslationUpsertOne) SetSummary(v string) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *PostTranslationUpsertOne) UpdateSummary() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateSummary()
	})
}

// ClearSummary clears the value of the "summary" field.
func (u *PostTranslationUpsertOne) ClearSummary() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearSummary()
	})
}

// SetContent sets the "content" field.
func (u *PostTranslationUpsertOne) SetContent(v string) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *PostTranslationUpsertOne) UpdateContent() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *PostTranslationUpsertOne) ClearContent() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearContent()
	})
}

// SetOriginalContent sets the "original_content" field.
func (u *PostTranslationUpsertOne) SetOriginalContent(v string) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetOriginalContent(v)
	})
}

// UpdateOriginalContent sets the "original_content" field to the value that was provided on create.
func (u *PostTranslationUpsertOne) UpdateOriginalContent() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateOriginalContent()
	})
}

// ClearOriginalContent clears the value of the "original_content" field.
func (u *PostTranslationUpsertOne) ClearOriginalContent() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearOriginalContent()
	})
}

// SetFullPath sets the "full_path" field.
func (u *PostTranslationUpsertOne) SetFullPath(v string) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetFullPath(v)
	})
}

// UpdateFullPath sets the "full_path" field to the value that was provided on create.
func (u *PostTranslationUpsertOne) UpdateFullPath() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateFullPath()
	})
}

// ClearFullPath clears the value of the "full_path" field.
func (u *PostTranslationUpsertOne) ClearFullPath() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearFullPath()
	})
}

// SetWordCount sets the "word_count" field.
func (u *PostTranslationUpsertOne) SetWordCount(v uint32) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetWordCount(v)
	})
}

// AddWordCount adds v to the "word_count" field.
func (u *PostTranslationUpsertOne) AddWordCount(v uint32) *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.AddWordCount(v)
	})
}

// UpdateWordCount sets the "word_count" field to the value that was provided on create.
func (u *PostTranslationUpsertOne) UpdateWordCount() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateWordCount()
	})
}

// ClearWordCount clears the value of the "word_count" field.
func (u *PostTranslationUpsertOne) ClearWordCount() *PostTranslationUpsertOne {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearWordCount()
	})
}

// Exec executes the query.
func (u *PostTranslationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PostTranslationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PostTranslationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PostTranslationUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PostTranslationUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PostTranslationCreateBulk is the builder for creating many PostTranslation entities in bulk.
type PostTranslationCreateBulk struct {
	config
	err      error
	builders []*PostTranslationCreate
	conflict []sql.ConflictOption
}

// Save creates the PostTranslation entities in the database.
func (_c *PostTranslationCreateBulk) Save(ctx context.Context) ([]*PostTranslation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PostTranslation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostTranslationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PostTranslationCreateBulk) SaveX(ctx context.Context) []*PostTranslation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostTranslationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostTranslationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PostTranslation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PostTranslationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PostTranslationCreateBulk) OnConflict(opts ...sql.ConflictOption) *PostTranslationUpsertBulk {
	_c.conflict = opts
	return &PostTranslationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PostTranslation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PostTranslationCreateBulk) OnConflictColumns(columns ...string) *PostTranslationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PostTranslationUpsertBulk{
		create: _c,
	}
}

// PostTranslationUpsertBulk is the builder for "upsert"-ing
// a bulk of PostTranslation nodes.
type PostTranslationUpsertBulk struct {
	create *PostTranslationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PostTranslation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(posttranslation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PostTranslationUpsertBulk) UpdateNewValues() *PostTranslationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(posttranslation.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(posttranslation.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(posttranslation.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PostTranslation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PostTranslationUpsertBulk) Ignore() *PostTranslationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PostTranslationUpsertBulk) DoNothing() *PostTranslationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PostTranslationCreateBulk.OnConflict
// documentation for more info.
func (u *PostTranslationUpsertBulk) Update(set func(*PostTranslationUpsert)) *PostTranslationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PostTranslationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PostTranslationUpsertBulk) SetUpdatedAt(v time.Time) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PostTranslationUpsertBulk) UpdateUpdatedAt() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *PostTranslationUpsertBulk) ClearUpdatedAt() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PostTranslationUpsertBulk) SetDeletedAt(v time.Time) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PostTranslationUpsertBulk) UpdateDeletedAt() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PostTranslationUpsertBulk) ClearDeletedAt() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *PostTranslationUpsertBulk) SetCreatedBy(v uint32) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *PostTranslationUpsertBulk) AddCreatedBy(v uint32) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *PostTranslationUpsertBulk) UpdateCreatedBy() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *PostTranslationUpsertBulk) ClearCreatedBy() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PostTranslationUpsertBulk) SetUpdatedBy(v uint32) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PostTranslationUpsertBulk) AddUpdatedBy(v uint32) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PostTranslationUpsertBulk) UpdateUpdatedBy() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PostTranslationUpsertBulk) ClearUpdatedBy() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *PostTranslationUpsertBulk) SetDeletedBy(v uint32) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *PostTranslationUpsertBulk) AddDeletedBy(v uint32) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *PostTranslationUpsertBulk) UpdateDeletedBy() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *PostTranslationUpsertBulk) ClearDeletedBy() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearDeletedBy()
	})
}

// SetSeo sets the "seo" field.
func (u *PostTranslationUpsertBulk) SetSeo(v *contentpb.SeoMeta) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetSeo(v)
	})
}

// UpdateSeo sets the "seo" field to the value that was provided on create.
func (u *PostTranslationUpsertBulk) UpdateSeo() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateSeo()
	})
}

// ClearSeo clears the value of the "seo" field.
func (u *PostTranslationUpsertBulk) ClearSeo() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearSeo()
	})
}

// SetPostID sets the "post_id" field.
func (u *PostTranslationUpsertBulk) SetPostID(v uint32) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetPostID(v)
	})
}

// AddPostID adds v to the "post_id" field.
func (u *PostTranslationUpsertBulk) AddPostID(v uint32) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.AddPostID(v)
	})
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *PostTranslationUpsertBulk) UpdatePostID() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdatePostID()
	})
}

// ClearPostID clears the value of the "post_id" field.
func (u *PostTranslationUpsertBulk) ClearPostID() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearPostID()
	})
}

// SetLanguageCode sets the "language_code" field.
func (u *PostTranslationUpsertBulk) SetLanguageCode(v string) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetLanguageCode(v)
	})
}

// UpdateLanguageCode sets the "language_code" field to the value that was provided on create.
func (u *PostTranslationUpsertBulk) UpdateLanguageCode() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateLanguageCode()
	})
}

// ClearLanguageCode clears the value of the "language_code" field.
func (u *PostTranslationUpsertBulk) ClearLanguageCode() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearLanguageCode()
	})
}

// SetTitle sets the "title" field.
func (u *PostTranslationUpsertBulk) SetTitle(v string) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PostTranslationUpsertBulk) UpdateTitle() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *PostTranslationUpsertBulk) ClearTitle() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearTitle()
	})
}

// SetSlug sets the "slug" field.
func (u *PostTranslationUpsertBulk) SetSlug(v string) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *PostTranslationUpsertBulk) UpdateSlug() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateSlug()
	})
}

// ClearSlug clears the value of the "slug" field.
func (u *PostTranslationUpsertBulk) ClearSlug() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearSlug()
	})
}

// SetSummary sets the "summary" field.
func (u *PostTranslationUpsertBulk) SetSummary(v string) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *PostTranslationUpsertBulk) UpdateSummary() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateSummary()
	})
}

// ClearSummary clears the value of the "summary" field.
func (u *PostTranslationUpsertBulk) ClearSummary() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearSummary()
	})
}

// SetContent sets the "content" field.
func (u *PostTranslationUpsertBulk) SetContent(v string) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *PostTranslationUpsertBulk) UpdateContent() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *PostTranslationUpsertBulk) ClearContent() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearContent()
	})
}

// SetOriginalContent sets the "original_content" field.
func (u *PostTranslationUpsertBulk) SetOriginalContent(v string) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetOriginalContent(v)
	})
}

// UpdateOriginalContent sets the "original_content" field to the value that was provided on create.
func (u *PostTranslationUpsertBulk) UpdateOriginalContent() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateOriginalContent()
	})
}

// ClearOriginalContent clears the value of the "original_content" field.
func (u *PostTranslationUpsertBulk) ClearOriginalContent() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearOriginalContent()
	})
}

// SetFullPath sets the "full_path" field.
func (u *PostTranslationUpsertBulk) SetFullPath(v string) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetFullPath(v)
	})
}

// UpdateFullPath sets the "full_path" field to the value that was provided on create.
func (u *PostTranslationUpsertBulk) UpdateFullPath() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateFullPath()
	})
}

// ClearFullPath clears the value of the "full_path" field.
func (u *PostTranslationUpsertBulk) ClearFullPath() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearFullPath()
	})
}

// SetWordCount sets the "word_count" field.
func (u *PostTranslationUpsertBulk) SetWordCount(v uint32) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.SetWordCount(v)
	})
}

// AddWordCount adds v to the "word_count" field.
func (u *PostTranslationUpsertBulk) AddWordCount(v uint32) *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.AddWordCount(v)
	})
}

// UpdateWordCount sets the "word_count" field to the value that was provided on create.
func (u *PostTranslationUpsertBulk) UpdateWordCount() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.UpdateWordCount()
	})
}

// ClearWordCount clears the value of the "word_count" field.
func (u *PostTranslationUpsertBulk) ClearWordCount() *PostTranslationUpsertBulk {
	return u.Update(func(s *PostTranslationUpsert) {
		s.ClearWordCount()
	})
}

// Exec executes the query.
func (u *PostTranslationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PostTranslationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PostTranslationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PostTranslationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
