// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attachment is the predicate function for attachment builders.
type Attachment func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Link is the predicate function for link builders.
type Link func(*sql.Selector)

// Menu is the predicate function for menu builders.
type Menu func(*sql.Selector)

// Photo is the predicate function for photo builders.
type Photo func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
